### ISSUE TITLE
option to export each unit as separate wav

### ISSUE THREAD

**Issue by yuxshao** [yuxshao/ptcollab#73]
makes it easier to eg input into corrscope

overdrive could be affected a bit, but theres possibly a workaround

**Comment by yuxshao** [comment]
Ahh interesting idea.. could work with the overdrive thing at least. Though it is a bit weird though since then you may have a single instrument jump across diff exports if you have segments where it has echo and other segments where it doesn't

**Comment by EwanGreen4** [comment]
I think this feature would have to be super configurable from the UI because it all depends on what the user wants to do. If they want to input it into something like corrscope, they may want to have each oscilloscope view as a group instead of as a unit for this exact reason -- if the song makes minimal use of effects, maybe not.

If it's to put the tracks together in another music software (for better mixing or something), they would definitely want everything to be exported per-unit

Might have to think of a good way to present this issue to the user in the UI

**Comment by yuxshao** [comment]
https://github.com/yuxshao/ptcollab/commit/5a6bea0dc4826aebc16157eedcf03d65d98a6a43
will probably package into release some time soon. but you can build from source in meantime

If people really need something for overdrive we can revisit

**Comment by EwanGreen4** [comment]
Um. Sweet
