### ISSUE TITLE
Allow exporting a project in multiple tracks

### ISSUE THREAD

**Issue by ArcOfDream** [yuxshao/ptcollab#79]
This is a feature request which would allow a user to then put the exported tracks in a DAW for further post-processing, for example. Only downside is that the overdrive effect would not work through this and would prolly have to be disabled.

This could potentially be integrated in the export dialog as an export mode: "Export full track" as the default .wav export and "Export as stems", which could export to a folder with the same name as the project and having the individual tracks named after units.

What do you think, though?

**Comment by yuxshao** [comment]
Seems good to me! There's a bit of discussion here about overdrive - https://github.com/yuxshao/ptcollab/issues/73
But it's probably useful enough to export by unit to start. @EwanGreen4 this is a thing I think you could probably take if you wanted. Otherwise I can probably try it in the next few days...

**Comment by EwanGreen4** [comment]
I'm willing to give it a shot but I have no real timeframe for you. A lot on my plate rn

**Comment by yuxshao** [comment]
No worries then! I may try to tackle it myself. But if you find you have
time LMK so I don't start on it too

**Comment by yuxshao** [comment]
https://github.com/yuxshao/ptcollab/commit/5a6bea0dc4826aebc16157eedcf03d65d98a6a43
will probably package into release some time soon. but you can build from source in meantime
